# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase:
    - rubocop.yml

require:
  - rubocop-rspec
  - database_validations/rubocop/cops

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
