default: &default
  adapter: postgresql
  encoding: unicode
  # For Postgres >= 9.2, you don't need to set pool size or username/password here
  # but usually you'd specify them, for example:
  # username: postgres
  # password:
  # host: localhost
  # port: 5432
  
development:
  <<: *default
  database: bicycle_shop_development

test:
  <<: *default
  database: bicycle_shop_test

production:
  <<: *default
  database: bicycle_shop_production
  # You'd typically configure credentials via environment variables in production
